/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:36a86b6f-a8f1-4b31-9ad2-87accd42e88b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_iqgTPPxbH",
    "aws_user_pools_web_client_id": "5gjcfj302ruecmsjthmhh89met",
    "oauth": {}
};


export default awsmobile;
